export const PAGE_META: Record<string, { title: string; subtitle: string }> = {
  '/patient': { title: 'Good day! 🌿', subtitle: '' },
  '/patient/profile': { title: 'My Profile', subtitle: 'Your personal health record' },
  '/patient/diseases': { title: 'Diseases', subtitle: 'All diagnosed conditions' },
  '/patient/medicines': { title: 'Medicines', subtitle: 'Current and past prescriptions' },
  '/patient/tracker': { title: 'Daily Tracker', subtitle: 'Mark medicines as taken, missed, or skipped' },
  '/patient/health': { title: 'Health Logs', subtitle: 'Vitals and daily health readings' },
  '/patient/symptoms': { title: 'Symptoms', subtitle: 'Log and track any health concerns' },
  '/patient/visits': { title: 'Appointments', subtitle: 'Upcoming and past appointments' },
  '/patient/reports': { title: 'Reports', subtitle: 'Adherence and health trend summaries' },
  '/patient/assistant': { title: 'AI Assistant', subtitle: 'Ask about medicines, symptoms, or first aid' },
  '/caregiver': { title: 'Caregiver Dashboard 👩⚕️', subtitle: '' },
  '/caregiver/patients': { title: 'My Patients', subtitle: 'View and manage the patients you care for' },
  '/caregiver/alerts': { title: 'Alerts', subtitle: 'Missed doses, low stock, and critical readings' },
  '/doctor': { title: 'Doctor Dashboard 🩺', subtitle: '' },
  '/doctor/patients': { title: 'My Patients', subtitle: 'Assigned patients and their clinical history' },
  '/doctor/appointments': { title: 'Appointments', subtitle: 'Scheduled visits and follow-ups' },
  '/doctor/alerts': { title: 'Alerts', subtitle: 'Critical updates across your patients' },
}
